### ISSUE TITLE
Do we need to change the Copyright © 2020 to 2021? (as per bottom of pages and license etc)

### ISSUE THREAD

**Issue by Doishy** [angrybacon/doomsday-wiki#123]
As per title.
Currently states "Copyright © 2020"
Should we change to 2021?

**Comment by angrybacon** [comment]
I think I read somewhere that the date doesn't to be updated and that it automatically extend to present date but I suppose it depends on country of hosting and could up to N years. I also read that removing the actual date would make the previous statement *more true*.

Can you confirm any of that? Yourself or someone around you more knowledgeable on the matter

**Comment by Doishy** [comment]
Emidln might know.

**Comment by angrybacon** [comment]
Is the current imlementation considered satisfactory? https://ddft.wiki/

![image](https://user-images.githubusercontent.com/5608624/136511652-dd885b0d-f038-49d3-a66f-4f82bd0a2184.png)
