### ISSUE TITLE
Add banner display images for main "Articles" list - Make it visually appealing.

### ISSUE THREAD

**Issue by Doishy** [angrybacon/doomsday-wiki#134]

**Comment by angrybacon** [comment]
There was no easy way to add banners in such a small space but more importantly, loading the article list would also download all visible banners at once (about 10 arts) and Scryfall doesn't provide small files for art crops. They're about 100 kB each with the resolution Scryfall provide them in 😢 

We could either host the files ourselves (tedious to maintain and that requires contributors to upload a sane version of the art) or find a service that provides smaller art version of cards

Feel free to re-open if you think the article list still needs the banners within

<img width="1315" alt="Screen Shot 2022-03-01 at 17 07 54" src="https://user-images.githubusercontent.com/5608624/156204842-5f02fc18-a0cf-4172-bccf-b7f913c0df44.png">
