### ISSUE TITLE
Split "Acronyms list" into two:

### ISSUE THREAD

**Issue by Doishy** [angrybacon/doomsday-wiki#135]
Split into two lists. First list is what is displayed in sidebar. Only contains "current" cards that are actively in use. 
Second list is the backend "master" list which displays all potential pile cards both past and present. 
@d8dk32 needs to help curate the list to ensure relevancy for DDFT specific cards.
Idea is minimal amount of "current" cards as possible.

Current:

AD:   'Abrupt Decay',
BS:   'Brainstorm',
BW:   'Burning Wish',
CR:   'Cabal Ritual',
CT:   'Cabal Therapy',
CoS:  'Cavern of Souls',
CoV:  'Chain of Vapor',
Con: 'Consider',
Dz: 'Daze',
DA:   'Deep Analysis',
DD:   'Doomsday',
DR:   'Dark Ritual',
Dur:  'Duress',
EF:   'Experimental Frenzy',
ET:   'Echoing Truth',
Em:   'Emrakul, the Aeons Torn',
EoA:  'Edge of Autumn',
EoE:  'Echo of Eons',
EtW:  'Empty the Warrens',
FoN: 'Force of Negation',
FoW:  'Force of Will',
IC:   'Infernal Contract',
IU:   'Ideas Unbound',
LDV:  "Lim-Dul's Vault",
LED:  "Lion's Eye Diamond",
LP:   'Lotus Petal',
Mm:   'Manamorphose',
PE: 'Prismatic Ending',
PT:   'Personal Tutor',
Pdt:  'Predict',
Pnd:  'Ponder',
PoN:  'Pact of Negation',
Pre:  'Preordain',
REB: 'Red Elemental Blast',
RiP:  'Rest in Peace',
SE:   'Surgical Extraction',
SI:   'Shelldock Isle',
SW:   'Street Wraith',
SotV: 'Spoils of the Vault',
StP:  'Swords to Plowshares',
Tef: 'Teferi, Time Raveler',
TO:   "Thassa's Oracle",
ToA:  'Tendrils of Agony',
Tsz:  'Thoughtseize',
VoS:  'Veil of Summer',

Master:

As above but also including:

  AoI:  'Act on Impulse',
  CB:   "Conjurer's Bauble",
  DW:   'Divining Witch',
  GP:   'Gitaxian Probe',
  LM:   'Laboratory Maniac',
  SdT:  "Sensei's Divining Top",
  TW:   'Three Wishes',

**Comment by d8dk32** [comment]
@angrybacon how much work would it be to show different acronyms lists depending on which section of the site you were looking at (i.e ddft chapters vs meandeck chapters)?
 I'd love to significantly shrink this list of acronyms, and not needed to clutter the list with Force of will or Tendrils when the deck you care about doesn't even play those cards would be nice
