### ISSUE TITLE
Remove DDEFT from welcome.md partial?

### ISSUE THREAD

**Issue by drynne0** [angrybacon/doomsday-wiki#219]
DDEFT is no longer in the sidebar, but is still listed among current variants in welcome.md. Maybe should be removed or moved to a Ned section at the bottom for defunct variants?

**Comment by angrybacon** [comment]
I left it on purpose as the pages are still online and the description for the deck is still true

That being said I missed the part where we introduce "3 main variants" being available from the sidebar. Probably worth 1. rewording that or 2. simply remove definition for DDEFT like you suggest 🤷

**Comment by drynne0** [comment]
Looks good to me, at least until we have some content for Citadel lists.
