### ISSUE TITLE
Get some new puzzles a brewin'

### ISSUE THREAD

**Issue by Doishy** [angrybacon/doomsday-wiki#37]
For both Echo and Meandeck 2.0 lists.

**Comment by angrybacon** [comment]
@Doishy You can have a look here https://github.com/angrybacon/doomsday-wiki/tree/master/puzzles and edit some of the old ones (and use the YAML syntax that @d8dk32 implemented) or list the deprecated ones and I'll delete them.

Don't bother too much about the organization that'll be another topic of discussion: I want users to be able to filter puzzles by difficulty, list or cards.

**Comment by Doishy** [comment]
@d8dk32  / @angrybacon please review puzzles (alpha, beta, gamma) and BUG Meandeck decklist for preperation for "go live". They should be ready but please just sense check the lot :) x :fox_face:

**Comment by Doishy** [comment]
New puzzles are in, might do a second wave sometime but will close this for now I thing.
