### ISSUE TITLE
Provide banners for recent articles

### ISSUE THREAD

**Issue by angrybacon** [angrybacon/doomsday-wiki#58]
Currently working on the layout it looks like this:

![image](https://user-images.githubusercontent.com/5608624/78893440-a239ae80-7a6b-11ea-82c0-54b28872e867.png)

For reference the images used above are respectively: 500x150, 200x150 and 300x150.

Ideally we would have images from the 4 most recent articles onward. All file sizes accepted, the smallest the better for the end-user. As far as ratio goes, anything will just *work* but images that are taller than their width will look bad on a narrow viewport like on mobiles.

The image would later be implemented as the article banner itself, so images with a width about twice the height would be the better fit I think. Could be perfected later on anyway.

**Comment by d8dk32** [comment]
This looks really good to me.
